version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt --break-system-packages
      - run:
          name: Install sdgen
          command: |
            pip3 install . --break-system-packages
      - run:
          name: Run tests
          command: pytest tests/ --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  test-cpp-gen:
    docker:
      - image: gcc:13
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            apt-get update && apt-get install -y python3 python3-pip
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt --break-system-packages
      - run:
          name: Install sdgen
          command: |
            pip3 install . --break-system-packages
      - run:
          name: Install C++ dependencies
          command: |
            apt-get update && apt-get install -y libyaml-cpp-dev nlohmann-json3-dev librapidxml-dev
      - run:
          name: Run C++ codegen and serialization tests with pytest
          command: |
            pytest tests-gen/ --junitxml=junit-cpp.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit-cpp.xml
workflows:
  build-and-test:
    jobs:
      - test-python
      - test-cpp-gen
